### ISSUE TITLE
Create Account Form

### ISSUE THREAD

**Issue by alexphelps** [alexphelps/gitjobs#2]
**Task List**
- [x] Create User Profile App and add foreign key for Account
- [x] Create a Form to sign up new company 
- [x] Auto sign the user in when they sign up
- [x] redirect to /dashboard when they sign up

**Form to create a new account**
- Company Name
- Company website link
- Company Logo
- User email
- Password

**Comment by alexphelps** [comment]
Needs more tests
