### ISSUE TITLE
Setup Search Filter

### ISSUE THREAD

**Issue by alexphelps** [alexphelps/gitjobs#5]
Wire up the search features so they actually work
* Search title / description / company
* Search job location

**Task List**
- [ ] Install Elasticsearch
- [ ] Install Haystack
- [ ] Create search indexes
- [ ] Create search results template
- [ ] Wire up search from homepage and all jobs page

**Comment by alexphelps** [comment]
https://docs.djangoproject.com/en/1.8/ref/models/querysets/#std:fieldlookup-startswith

https://docs.djangoproject.com/en/1.8/ref/models/querysets/#std:fieldlookup-contains
